version: '3.8'
services:
  henry-postgres:
    image: postgres:latest
    container_name: henry-postgres
    environment:
      POSTGRES_USER: $dockerPostgresUsername
      POSTGRES_PASSWORD: $dockerPostgresPassword
      POSTGRES_DB: $dockerPostgresDatabase
      POSTGRES_INITDB_ARGS: "-c wal_level=logical -c max_replication_slots=4 -c max_wal_senders=4"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  henry-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  henry-kafka:
    image: wurstmeister/kafka:latest
    container_name: henry-kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://henry-kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: henry-zookeeper:2181
      KAFKA_REPLICATION_FACTOR: 1
    ports:
      - "9094:9094"
    depends_on:
      - henry-zookeeper

  henry-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: henry-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  henry-debezium:
    image: debezium/connect:2.7.3.Final
    container_name: henry-debezium
    environment:
      BOOTSTRAP_SERVERS: henry-kafka:9092
      GROUP_ID: debezium
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    ports:
      - "8083:8083"
    depends_on:
      - henry-kafka
      - henry-postgres

  henry-rabbitmq:
    image: rabbitmq:management
    container_name: henry-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

  henry-redis:
    image: redis:latest
    container_name: henry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  es_data:
  redis_data:
