version: '3.8'
services:
  henry-postgres:
    image: postgres:latest
    container_name: henry-postgres
    environment:
      POSTGRES_USER: henry
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: henry-event
    ports:
      - "9990:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  henry-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9991:9200"
      - "9981:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  henry-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: henry-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: henry-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://henry-kafka:9992
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9992:9092"
    depends_on:
      - henry-zookeeper

  henry-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: henry-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "9993:2181"

  henry-debezium:
    image: debezium/connect:latest
    container_name: henry-debezium
    environment:
      BOOTSTRAP_SERVERS: henry-kafka:9992
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PRODUCER_MAX_BLOCK_MS: "5000"
    ports:
      - "9994:8083"
    depends_on:
      - henry-kafka
      - henry-postgres

  henry-rabbitmq:
    image: rabbitmq:management
    container_name: henry-rabbitmq
    ports:
      - "9995:5672"
      - "9985:15672" # Management UI

  henry-redis:
    image: redis:latest
    container_name: henry-redis
    ports:
      - "9996:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  es_data:
  redis_data:
